name: Deploy Application

on:
  workflow_run:
    workflows: ["Build Application"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2



      # Add your deployment steps here
