name: RepoB Workflow

on:
  repository_dispatch:
    types:
      - repo-a-workflow-completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3




